name: "Migration of ADO Pipeline to GHA Pipeline"
description: "Provide ADO Migration Details"
title: "Migrating ADO pipeline to GHA using GITHUB Actions Importer"
labels:
  - migration
  - automation

body:
  - type: input
    id: Org-name
    attributes:
      label: "Repository Organization"
      description: "Enter the name of the Repo-organization name where the workflow will be saved"
      placeholder: "e.g., Sample-org"
    validations:
      required: true

  - type: input
    id: Repo-name
    attributes:
      label: "Repository name"
      description: "Enter the name of the Repo-name where the workflow will be saved"
      placeholder: "e.g., sample-repo"
    validations:
      required: true
      
  - type: input
    id: AZURE_DEVOPS_ORG
    attributes:
      label: "AZURE ORGANIZATION NAME"
      description: "Enter the name of the AZURE DEVOPS ORGANIZATION"
      placeholder: "e.g., SampleAzureOrganization"
    validations:
      required: true

  - type: input
    id: AZURE_DEVOPS_PROJECT
    attributes:
      label: "AZURE PROJECT NAME"
      description: "Enter the name of the AZURE DEVOPS PROJECT"
      placeholder: "e.g., SampleAzureProject"
    validations:
      required: true
      
  - type: input
    id: Pipeline-id
    attributes:
      label: "Azure Pipeline-id"
      description: "Enter the Pipeline-id that needs to be migrated"
      placeholder: "e.g., 1562"
    validations:
      required: true
  
  - type: dropdown
    id: runtype
    attributes:
      label: "Run-Type"
      description: "Select between Audit and Dry-run"
      options:
        - "Dry-run"
        - "Audit"
    validations:
      required: true
