name: Payment_Services/Payment_Diversity_[CNP]/MGMResorts.pd-payments-audit-trail
on:
  push:
    branches:
    - feature/*
    - develop
    - main
    paths:
    - "*"
    - "!infrastructure-templates/*"
  pull_request:
    branches:
    - feature1
env:
  MAVEN_CACHE_FOLDER: "${{ runner.workspace }}/.m2/repository"
  MAVEN_OPTS: UPDATE ME
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # This item has no matching transformer
#     - task: JavaToolInstaller@0
#       inputs:
#         versionSpec: '17'
#         jdkArchitectureOption: x64
#         jdkSourceOption: PreInstalled
    - name: Maven Build
      run: |-
        mvn clean package
        mvn azure-functions:package
    # The following script preserves the globbing behavior of the CopyFiles task.
    # Refer to this transformer's documentation for an alternative that will work in simple cases.
    - uses: actions/github-script@v7.0.0
      env:
        TARGET_FOLDER: "${{ runner.temp }}"
        SOURCE_FOLDER: "${{ github.workspace }}/"
        CONTENTS: 'azure/**
          '
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const target = path.resolve(process.env.TARGET_FOLDER)
          process.chdir(process.env.SOURCE_FOLDER || '.')
          if (process.env.CLEAN_TARGET_FOLDER === 'true') await io.rmRF(target)
          const flattenFolders = process.env.FLATTEN_FOLDERS === 'true'
          const options = {force: process.env.OVERWRITE === 'true'}
          const globber = await glob.create(process.env.CONTENTS || '**')
          for await (const file of globber.globGenerator()) {
            if ((await fs.lstat(file)).isDirectory()) continue
            const filename = flattenFolders ? path.basename(file) : file.substring(process.cwd().length)
            const dest = path.join(target, filename)
            await io.mkdirP(path.dirname(dest))
            await io.cp(file, dest, options)
          }
    - name: Zip files
      run: 7z u ${{ runner.temp }}/functionapp.zip ./${{ github.workspace }}/target/azure-functions/pd-payments-audit-trail//*
    - name: Publish audit artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        name: "${{ github.run_id }}-Audit"
        path: "${{ runner.temp }}"
